import { ForumMessage } from './forum.message';

export const FORUM_MESSAGES: ForumMessage[] = [
  { id: 1,
	author: 'Betrand',
	content: "Ceci est le premier post sur le forum" ,
	timestamp: "aaaaaaa la daaate j'aime pas caa",
	vote: 2,
	tag: "RES"  },
  { id: 2,
	author: 'Betrand',
	content: "je spamm deejaaa le forum " ,
	timestamp: "aaaaaaa la daaate j'aime pas caa",
	vote: -2,
	tag:"RES" },
  { id: 3,
	author: 'Betrand',
	content: "coucou c'est encore moi ",
	timestamp: "aaaaaaa la daaate j'aime pas caa", 
	vote: -10,
	tag: "RES"  },

	{ id: 4,
	author: 'Clark',
	content: "Le projet est cool" ,
	timestamp: "aaaaaaa la daaate j'aime pas caa",
	vote: 2,
	tag: "PRO"  },
  { id: 5,
	author: 'Roman',
	content: "mais ca prends du temps " ,
	timestamp: "aaaaaaa la daaate j'aime pas caa",
	vote: -2,
	tag:"PRO" },
  { id: 6,
	author: 'Guub',
	content: "vous avez raison ouais ",
	timestamp: "aaaaaaa la daaate j'aime pas caa", 
	vote: -10,
	tag: "PRO"  },
  
];